

fill_optional <- function(opts) {
  optionals <-
    list(
      type = NULL,
      partial = FALSE,
      description = "",
      check = NULL
    )
  for (k in seq_along(opts)) {
    opts[[k]] <- utils::modifyList(
      optionals,
      opts[[k]]
    )
  }
  opts
}



extract_functions <- function(config, remove_prefix = TRUE) {
  opts <- fill_optional(config$options)
  flist <- vector(
    mode = "list",
    length = length(
      opts
    )
  )
  for (k in seq_along(
    flist
  )) {
    fn <- function() {}
    formals(fn) <-
      eval(
        substitute(
          alist(
            value = NULL,
            ... = ,
            .default = default
          ),
          opts[[k]]
        )
      )
    names(opts[[k]]) <- paste0(".", names(opts[[k]]))
    names(opts[[k]])[opts[[k]] == ".default"] <- "default"
    body(fn) <- substitute(
      {
        ropt_get(
          name = .name,
          value = value,
          type = .type,
          default = .default,
          check = .check,
          partial = .partial,
          args = list(
            ...
          )
        )
      },
      opts[[k]]
    )
    flist[[k]] <- fn
  }
  opt_names <- vapply(
    opts,
    `[[`,
    ".name",
    FUN.VALUE = character(
      1L
    )
  )
  if (remove_prefix) {
    opt_names <- gsub("^[^.]+?\\.", "", opt_names)
  }
  names(flist) <- opt_names
  flist[order(
    names(
      flist
    )
  )]
}

#' Generate package option object
#'
#' Generates an R file containing option retrieval and validation code, along with documentation.
#' See `?roptgen.options` for detailed descriptions of each option referenced.
#' @param config Defaults to option `roptgen.file.in`. The location of
#'  the .yaml file describing the package options. See `system.file("config.yaml", package = "roptgen")`
#'  for an example of this format
#' @param object Defaults to option `roptgen.object`. Name of object which will hold option accessor
#'  functions and be exported from your package.
#' @param inline Defaults to option `roptgen.inline`.Not yet implemented. Whether to inline all code in your project.
#'  This allows not taking a dependency on roptgen, not even in Suggests. This might be useful as
#'  a starting point for code you then modify by hand, or just to keep dependencies to a minimum.
#' @param file Defaults to option `roptgen.file`, the default of which will be "<package>-options.R".
#'  The file for the generated option code.
#' @param tests Defaults to option `roptgen.tests`, whether to copy tests or not. Not yet implemented.
#' @param strip_prefix Defaults to option `roptgen.strip.prefix`. Whether to remove the package name from
#'   the option object's elements, e.g., `roptgen_options$roptgen.file.in()` vs `roptgen_options$file.in()`.
#' @return No return value.
#' @export
roptgen <- function(config = NULL, object = NULL, inline = NULL,
                    file = NULL,
                    tests = NULL, strip_prefix = NULL) {
  if (is.null(config)) {
    config <- roptgen_options$file.in()
  }
  if (is.character(config)) {
 config <- yaml::yaml.load_file(config,
                         as.named.list = TRUE,
                         eval.expr = TRUE
    )
  }
configuration <-  extract_functions(config,TRUE)
doc <- extract_documentation(config)
obj_name <- roptgen_options$object(object)
file_out <- roptgen_options$file.out(file)
code <-  mapply(writefun, names(configuration), unname(configuration), USE.NAMES = FALSE)
if (roptgen_options$inline(inline)) {
  helper_file <- paste0(file_out, "-helpers.R")
  doc <- c(doc, paste("#' @include", basename(helper_file)))
}
file_contents <- make_file_contents(obj_name, code, doc)
writeLines(file_contents, paste0(file_out, ".R"))
if (roptgen_options$inline(inline)) {
  file.copy(system.file("inline.R", package = "roptgen"), helper_file)
}
}

writefun <- function(name, fn) {
  fndef <- sprintf(
    "%s = %s",
    name,
    paste0(
      deparse(fn, width.cutoff = 70),
      collapse = "\n"))
  fndef <- gsub("^\\n+|\\n+$", "", fndef)
  fndef <- gsub("function \\(", "function(", fndef)
  gsub("\\n\\{", "{", fndef)
}

extract_documentation <- function(config) {
  docs <- gsub("\\s+", " ", config$overview$documentation)
  opt_docs <- lapply(config$options, document_option)
  docs <- strsplit(docs, "#' ", fixed = TRUE)[[1]][-1]
  docs[length(docs)] <- gsub("\\n", "", docs[length(docs)])
  docs <- c(docs, "@section Options:", unlist(opt_docs))
  paste("#'", docs)
}

document_option <- function(x) {
 strwrap(paste0("* `", x$name, "`: ", gsub("\\n+", "\\n", x$description)), width = 100, exdent = 4)
}

make_file_contents <- function(object, code, doc = NULL) {
contents <- c(paste("# Code auto-generated by roptgen", utils::packageVersion("roptgen")),"",
    doc,
    "#' @export",
    paste(object, " <- function() {}"),
    paste0('rm(', object, ')'),
    paste(object, " <- list("),
    paste(code, collapse = ",\n\n"),
    ")"
    )
}

roptgen_test_dir <- function() {
  testvar <- getOption("roptgen.test")
  if (is.character(testvar)) {
    if (testvar == 'tinytest')
      'inst/tinytest'
  } else {
    "tests/testthat"
  }
}


