config_get <- function(name, value, type, default, check, args, partial) {
  return_value_if_present_and_valid(name, value, type, default, check, args, partial)
  return_option_if_present_and_valid(name, value, type, default, check, args, partial)
  call_if_fun(default, args)
}
call_if_fun <- function(fn, args) {
  if (is.function(fn)) {
    return(do.call(fn, args))
  }
  fn
}
return_option_if_present_and_valid <- function(name, value, type, default, check, args, partial) {
  opt <- getOption(name)
  if (is.null(opt)) {
    return()
  }
  opt <- roptgen_validate(type, name, partial)(opt)
  if (!is.null(check)) {
    opt <- call_if_fun(opt, args)
    pass <- check(opt)
    if (!pass) {
      warning("Value of ",
        dQuote(name),
        " did not pass check function. ",
        "Using the default instead.",
        call. = FALSE
      )
      return()
    }
  }
  do.call(return, list(opt), envir = sys.frame(-1))
}

return_value_if_present_and_valid <-
  function(name, value, type, default, check, args, partial) {
    if (is.null(value)) {
      return()
    }

    value <- roptgen_validate(type, name, partial)(value)
    if (!is.null(check)) {
      value <- call_if_fun(value, args)
      pass <- check(value)
      if (!pass) {
        warning(
          dQuote(value),
          " did not pass check function. ",
          "Using value of option, ",
          dQuote(name),
          " instead, or the default if unset.",
          call. = FALSE
        )
        return()
      }
    }
    do.call(return, list(value), envir = sys.frame(-1))
  }


fill_optional <- function(config) {
  optionals <-
    list(
      type = NULL,
      partial = FALSE,
      description = "",
      check = NULL
    )
  for (k in seq_along(config$options)) {
    config$options[[k]] <- modifyList(
      optionals,
      config$options[[k]]
    )
  }
  config
}

scratch_config_load <- function() {
  config <- yaml::yaml.load_file("inst/config.yaml",
    as.named.list = TRUE,
    eval.expr = TRUE
  )

  fill_optional(config)
}

config_to_functions <- function(config, remove_prefix = TRUE) {
  flist <- vector(
    mode = "list",
    length = length(
      config$options
    )
  )
  for (k in seq_along(
    flist
  )) {
    fn <- function() {}
    formals(fn) <-
      eval(
        substitute(
          alist(
            value = NULL,
            ... = ,
            .default = default
          ),
          config$options[[k]]
        )
      )
    names(config$options[[k]]) <- paste0(".", names(config$options[[k]]))
    body(fn) <- substitute(
      {
        config_get(
          name = .name,
          value = value,
          type = .type,
          default = .default,
          check = .check,
          partial = .partial,
          args = list(
            ...
          )
        )
      },
      config$options[[k]]
    )
    flist[[k]] <- fn
  }
  opt_names <- vapply(
    config$options,
    `[[`,
    ".name",
    FUN.VALUE = character(
      1L
    )
  )
  if (remove_prefix) {
    opt_names <- gsub("^[^.]+?\\.", "", opt_names)
  }
  names(flist) <- opt_names
  flist[order(
    names(
      flist
    )
  )]
}
# This needs to be run after absolutely everything else.
roptgen <- function(config = NULL, object = NULL, inline = NULL,
                    file = NULL,
                    tests = NULL, strip_prefix = NULL) {
  if (is.null(config)) {
    config <- roptgen_options$file.in()
  }
  if (is.character(config)) {
 config <- yaml::yaml.load_file(config,
                         as.named.list = TRUE,
                         eval.expr = TRUE
    )
  }
configuration <-  config_to_functions(config, FALSE)
doc <- configuration$overview$documentation
obj_name <- "roptgen_options"
file_out <- roptgen_options$file.out()
code <-  mapply(writefun, names(configuration), unname(configuration), USE.NAMES = FALSE)
if (roptgen_options$inline()) {
  helper_file <- paste0(file_out, "-helpers.R")
  doc <- c(doc, paste("#' @include", basename(helper_file)))
}
file_contents <- make_file_contents(obj, code, doc)
writeLines(file_contents, paste0(file_out, ".R"))
if (roptgen_options$inline()) {
  writeLines(readLines(system.file("inline.R"), package = "roptgen"),
             con = helper_file)
}
}
# configuration <-  config_to_functions(config)
#
writefun <- function(name, fn) {
  gsub("\n+", "\n", sprintf("%s <- %s", name, paste0(deparse(fn), collapse = "\n")))
}

make_file_contents <- function(object, code, doc = NULL) {
  c(paste("# Auto-generated by roptgen", packageVersion("roptgen")),
    "",
    doc,
    paste(option_obj," <- list("),
    "",
    paste(code, collapse = ",\n\n"),
    ")"
    )
}


# code <-  mapply(writefun, names(configuration), unname(configuration))
# writeLines(res, 'newfile.R')
# #
# #  all <- c(
# #    "",
# #    paste("# Auto-generated by roptgen", packageVersion("roptgen")),
# #    "",
# #    paste(option_obj," <- list("),
# #    "",
# #    paste(code, collapse = ",\n\n"),
# #    "",
# #    ")"
# #  )
#
#
#
# config_to_docs <- function(config) {
# descs <- vapply_1c(config, `[[`, "description")
# if (any(names(config) == "overview")) {
#
# }
# }
