# Code auto-generated by roptgen 0.1.0

#' @title User-level configuration for `r basename(getwd())` 
#' 
#' @description Configure `r basename(getwd())` to your liking. Options can be set in any of the following ways: 
#' 1. In \R via `options()`, where the name should be `roptgen.<name>`. 
#' 
#' 2. Via environment variables, replacing the periods in the option name with underscores. For example, 
#' the option 'roptgen.test.dir' becomes the environment variable `ROPTGEN_TEST_DIR`. 
#' If both the \R option and environment variable are present, the 
#' \R option takes precedence. 
#' 
#' 3. Some functions expose arguments which use the value of an option as the default. These can 
#' be overridden when needed. 
#' 
#' If an invalid option is provided, functions may either fall back to the default or error, presenting 
#' the valid options. 
#' 
#' Environment variables may be preferable over \R options since environment variables will also be 
#' available to any child processes. To set these environment variables or \R options across many projects, 
#' consider using an .Rprofile or .Renviron file, as documented in ?.Renviron. 
#' @section Options:
#' * `roptgen.object`: The name of the object which the options will be assigned to. Defaults to
#'     "config". It must be a syntactically valid R name.n
#' * `roptgen.file.in`: The path to the yaml file documenting package options. Defaults to
#'     inst/options.yaml.n
#' * `roptgen.file.out`: The file path to write the generated code to. Defaults to `R/options`. The
#'     extension will be set automatically.n
#' * `roptgen.inline`: Whether to inline all code which roptgen depends on for reading and validating
#'     options. If `TRUE`, the helper file will be the roptgen.file.out option with '-helpers'
#'     appended. The benefit of inlining is you do not need to take a dependency on roptgen (not even
#'     in Suggests!), the drawback, from certain perspectives, is you won't benefit from any bug fixes
#'     in roptgen after you have generated your option file, unless you regenerate it. One day, there
#'     will be an extensive suite of tests, which can also be copied into your project.n
#' * `roptgen.test`: Whether to copy tests into your package. If your tests are not in the standard
#'     location for the testing framework, or you are not developing a package, also set
#'     "roptgen.test.dir". Defaults to `FALSE`, and not copying tests into your package.n
#' * `roptgen.test.dir`: The directory to copy the tests. Make sure to also set "roptgen.test".n
#' * `roptgen.test.file`: The file which will contain the tests. It will be overwritten, so do not
#'     include with another set of tests.n
#' @export
roptgen_options  <- function() {}
rm(roptgen_options)
roptgen_options  <- list(
file.in = function(value = NULL, ..., .default = "inst/options.yaml") {
    ropt_get(name = "roptgen.file.in", value = value, type = "", default = "inst/options.yaml", 
        check = function(...) 
        .Internal(file.exists(c(...))), partial = FALSE, args = list(...))
},

file.out = function(value = NULL, ..., .default = "R/options") {
    ropt_get(name = "roptgen.file.out", value = value, type = "", default = "R/options", 
        check = function(...) 
        .Internal(file.exists(c(...))), partial = FALSE, args = list(...))
},

inline = function(value = NULL, ..., .default = FALSE) {
    ropt_get(name = "roptgen.inline", value = value, type = c(TRUE, FALSE
    ), default = FALSE, check = NULL, partial = FALSE, args = list(...))
},

object = function(value = NULL, ..., .default = "roptgen_options") {
    ropt_get(name = "roptgen.object", value = value, type = "", default = "roptgen_options", 
        check = function(x) 
        {
            if (make.names(x) != x) {
                stop("Option \"roptgen.object\" must be a syntactically valid R name.")
            }
            else TRUE
        }, partial = FALSE, args = list(...))
},

test = function(value = NULL, ..., .default = FALSE) {
    ropt_get(name = "roptgen.test", value = value, type = "list(FALSE, c(\"tinytest\", \"testthat\")", 
        default = FALSE, check = NULL, partial = FALSE, args = list(...))
},

test.dir = function(value = NULL, ..., .default = function() 
roptgen_test_dir()) {
    ropt_get(name = "roptgen.test.dir", value = value, type = "", default = function() 
    roptgen_test_dir(), check = function(paths) 
    .Internal(dir.exists(paths)), partial = FALSE, args = list(...))
},

test.file = function(value = NULL, ..., .default = "test-roptgen-options.R") {
    ropt_get(name = "roptgen.test.file", value = value, type = "", default = "test-roptgen-options.R", 
        check = NULL, partial = FALSE, args = list(...))
}
)
